#!/usr/bin/env bash
#  The redirection must be a “301 Moved Permanently”
#  You answer file should be a Bash script containing commands to 
#  automatically configure a Ubuntu machine to respect above requirements
#  Using what you did with 1-install_nginx_web_server, 
#  write 3-redirection so that it configures a brand new Ubuntu machine 
#  to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html

new_str="\\\trewrite ^/redirect_me https://www.linkedin.com/in/esere-cynthia-b11987186;"
sudo sed -i "421 $new_str" /etc/nginx/sites-available/default
sudo service nginx restart
