#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "
listen 3284-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 3284-web-01 52.201.222.26 check port 80
        server 3284-web-02 100.25.197.0 check port 80
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
